# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9iGY1Pn6qh41YSSuGkfW4dmDT3PUdDK

# 多语言智能客服 Demo（MVP）
跨境电商场景：意图识别 → FAQ 知识库锚定回复 → 多语言直接生成 → 高风险转人工
基于智谱 GLM API | 配套完整售前方案文档见文末链接

## Prompt 迭代记录

### v1  发现的问题
- 德语：格变错误（das Artikel → 应为 den）、动词误用（"Bringen ... ab"）、缺失问候与结尾结构，商务语境显得失礼
- 法语：信息正确但无结尾礼貌语，略生硬
- 中文转人工摘要："dispute the charge with my bank" 被弱化译为"向银行投诉费用"，未识别 chargeback（拒付）的资金与风控风险

### v2 修复措施
1. 回复生成 prompt 增加结构约束：要求按目标市场惯例添加问候语与礼貌结尾
2. 增加语言质量自检约束：要求按母语者标准检查性数格与动词搭配，禁止英语直译
3. 转人工摘要 prompt 增加风险分级规则：涉及拒付/法律行动须标注"高优先级"并说明商业风险

### v2 结果与残留风险
- 修复：问候/结尾结构、敬称（Sie/vous）、摘要风险分级（chargeback 被正确标为高优先级）
- 未修复：德语形态句法错误以**随机位置**持续出现（v2: "Um ein Artikel"；v3 复跑: "das betreffende Artikel"、"die vorfinanzierte Etikette"——Etikett 为中性名词）
- 新发现：知识库信息漂移（"prepaid label" 在改写中变为"指定退货单/vorfinanziert"，预付邮资这一关键信息失真）；英语回复一次泄漏模板占位符 "[Your Name]"；多次运行结构一致性无保障

### 结论
Prompt engineering 可有效约束**语用结构与业务规则**（问候、敬称、风险分级），但无法补足轻量模型在形态复杂语言（德语）上的**生成能力上限**。生产化建议：英/法语种用轻量模型控制成本；德语升级模型档位或增加规则质检层（格变校验 + 关键事实比对 + 输出格式校验）。

### 原始输出对比（德语用例："Wie kann ich meine Bestellung zurückgeben?"）

**v1 输出**（无结构与语言质量约束）：

> Gehen Sie zu "Meine Bestellungen", wählen Sie **das Artikel** aus, klicken Sie auf "Rücksendung" und drucken Sie das vorbezahlte Etikett aus. **Bringen Sie die Sendung in jedem örtlichen Postamt ab.**

问题：格变错误（das→den Artikel）；动词误用（"abbringen"，应为 abgeben）；"in jedem" 系英语 any 直译；无问候语、无结尾,商务语境失礼。

**v2 输出**（增加结构约束 + 母语者自检约束后）：

> Guten Tag,
>
> **Um ein Artikel zurückzugeben**, gehen Sie zu "Meine Bestellungen", wählen Sie den Artikel aus, klicken Sie auf "Rücksendung" und drucken Sie **das vorgesehene Rücksendezettel** aus. **Legen Sie die Sendung in einem beliebigen Postamt ab.**
>
> Für weitere Unterstützung stehe ich gerne zur Verfügung.
>
> Mit freundlichen Grüßen,
> Ihr Kundenservice-Team von OutBound

结果： 问候/结尾结构修复，主句格变正确； 同类格变错误转移至新位置（ein→einen Artikel；das→den Rücksendezettel，Zettel 为阳性）； 动词搭配仍错（ablegen）；
信息漂移：知识库 "prepaid label"（预付邮资）被改写为 "vorgesehene Rücksendezettel"（指定退货单），关键信息失真。

**v3 复跑**（同 v2 prompt,验证稳定性）：

> Sie können Ihre Bestellung einfach zurückgeben, indem Sie in Ihrem Kundenkonto unter "Meine Bestellungen" **das betreffende Artikel** auswählen, auf "Rücksendung anfordern" klicken und **die vorfinanzierte Etikette** ausdrucken. **Schicken Sie die Packung an jedem Postamt ab.**

结果：格变错误再次换位置出现（das betreffende Artikel；die Etikette——Etikett 为中性）；"prepaid" 再次漂移为 "vorfinanziert"；动词搭配仍错。三轮中错误位置均不同 → 证明系模型德语生成能力边界,非 prompt 指令问题。

### 附：转人工摘要 v1/v2 对比（英语投诉用例）

**v1**：【建议处理动作】建议联系客户，尽快安排与经理的沟通,并解决包裹丢失问题
**v2**（增加风险分级规则后）：【建议处理动作】**高优先级**，联系客户解决问题，**避免客户进行拒付，降低商业风险**

结果： chargeback 风险被正确识别并分级,业务规则类约束 prompt 可稳定修复。
"""

!pip install zhipuai

import os
from getpass import getpass
os.environ["ZHIPUAI_API_KEY"] = getpass("API key: ")

FAQ = [
  {"id": 1, "topic": "shipping", "q": "How long does delivery take to France/Germany/Spain?", "a": "Standard shipping to EU countries takes 7-12 business days. Express shipping (DHL) takes 3-5 business days and costs EUR 12.99 extra."},
  {"id": 2, "topic": "shipping", "q": "Do you ship to my country?", "a": "We ship to UK, France, Germany, Spain and Italy. We do not currently ship to other countries."},
  {"id": 3, "topic": "shipping", "q": "How can I track my order?", "a": "A tracking link is emailed within 24 hours of dispatch. You can also track on our website under My Orders."},
  {"id": 4, "topic": "shipping", "q": "What are the shipping costs?", "a": "Free standard shipping on orders over EUR 49. Below that, standard shipping is EUR 5.99."},
  {"id": 5, "topic": "returns", "q": "What is your return policy?", "a": "30-day free returns for unused items in original packaging. Refunds are processed within 5-7 business days after we receive the item."},
  {"id": 6, "topic": "returns", "q": "How do I return an item?", "a": "Go to My Orders, select the item, click Return, and print the prepaid label. Drop the parcel at any local post office."},
  {"id": 7, "topic": "returns", "q": "Can I exchange instead of refund?", "a": "Yes, exchanges for a different size or colour are free. Select Exchange instead of Refund in the return flow."},
  {"id": 8, "topic": "product", "q": "What are the dimensions of the foldable storage box?", "a": "The foldable storage box measures 40x30x25cm and holds up to 15kg. It is made of recycled PP plastic."},
  {"id": 9, "topic": "product", "q": "Are your products safe for children?", "a": "All our home products are EN 71 certified. Small parts warnings are listed on each product page where applicable."},
  {"id": 10, "topic": "product", "q": "What material are the bamboo shelves made of?", "a": "100% FSC-certified moso bamboo with a water-based, food-safe lacquer finish."},
  {"id": 11, "topic": "product", "q": "Is assembly required? Are tools included?", "a": "Most furniture items require simple assembly. All necessary tools and illustrated instructions are included in the box."},
  {"id": 12, "topic": "payment", "q": "What payment methods do you accept?", "a": "We accept Visa, Mastercard, PayPal, Klarna, and Apple Pay. We do not accept bank transfers."},
  {"id": 13, "topic": "payment", "q": "Can I get an invoice for my company?", "a": "Yes, enter your VAT number at checkout and a company invoice will be emailed automatically."},
  {"id": 14, "topic": "payment", "q": "Why was my payment declined?", "a": "Most declines come from the card issuer. Please verify your billing address matches your card, or try another payment method."},
  {"id": 15, "topic": "order", "q": "Can I change or cancel my order?", "a": "Orders can be changed or cancelled within 2 hours of placement via My Orders. After that the order enters fulfilment and cannot be modified."},
  {"id": 16, "topic": "order", "q": "I received a damaged item, what should I do?", "a": "We are sorry! Please send a photo of the damage via the contact form within 14 days, and we will send a free replacement or full refund - no return needed."},
  {"id": 17, "topic": "order", "q": "My order is missing an item.", "a": "Orders may ship in separate parcels. Check your dispatch emails; if an item is still missing after all parcels arrive, contact us with your order number."},
  {"id": 18, "topic": "warranty", "q": "What warranty do you offer?", "a": "All products carry the EU statutory 2-year warranty. Electrical items carry an additional 1-year manufacturer warranty."},
  {"id": 19, "topic": "account", "q": "How do I reset my password?", "a": "Click Forgot Password on the login page and follow the email link. The link is valid for 30 minutes."},
  {"id": 20, "topic": "discount", "q": "Do you have discount codes for first orders?", "a": "Yes, sign up to our newsletter for a 10% first-order code. Codes cannot be combined with other promotions."},
]

import os, json, re
from zhipuai import ZhipuAI

client = ZhipuAI(api_key=os.environ["ZHIPUAI_API_KEY"])
MODEL = "glm-4-flash"

def call(messages, max_tokens=500):

    resp = client.chat.completions.create(
        model=MODEL, messages=messages, max_tokens=max_tokens,
    )
    return resp.choices[0].message.content

def extract_json(text):

    m = re.search(r"\{.*\}", text, re.DOTALL)
    return json.loads(m.group()) if m else {}

def step1_classify(message):
    prompt = f"""You are an intent classifier for an e-commerce customer service system.
Analyze this customer message and respond ONLY with JSON, no markdown, no other text:
{{"language": "<en/fr/de/es/it/other>", "topic": "<shipping/returns/product/payment/order/warranty/account/discount/complaint/legal/other>", "escalate": <true if the message involves a complaint, legal threat, dispute, or strong negative emotion, else false>}}

Customer message: {message}"""
    return extract_json(call([{"role": "user", "content": prompt}], 200))

def step2_retrieve(message, topic, top_k=3):
    candidates = [x for x in FAQ if x["topic"] == topic] or FAQ
    listing = "\n".join(f'{x["id"]}. {x["q"]}' for x in candidates)
    prompt = f"""Customer question: {message}
Which FAQ entries (max {top_k}) are most relevant? Respond ONLY with JSON like {{"ids": [1,2]}}. If none are relevant, return {{"ids": []}}.
FAQ list:
{listing}"""
    ids = extract_json(call([{"role": "user", "content": prompt}], 100)).get("ids", [])
    return [x for x in FAQ if x["id"] in ids]

def step3_answer(message, language, retrieved):
    kb = "\n".join(f"Q: {x['q']}\nA: {x['a']}" for x in retrieved)
    system = f"""You are the customer service agent for OutBound, a home-goods e-commerce brand.
Rules:
- Reply in the customer's language: {language}
- Use the appropriate formality for that market (e.g. German: Sie-form; French: vous; Spanish: usted for first contact)
- Base your answer ONLY on the knowledge base below. If the answer is not in it, say you will forward the question to a human colleague - never invent shipping promises or policies.
- Tone: warm, concise, professional. Max 120 words.
- Structure: open with an appropriate greeting for the language/market, end with a polite closing offering further help
- Before finalizing, review your reply for grammatical correctness (gender, case, verb-preposition collocations) as a native speaker would; avoid literal translations of English phrasing

Knowledge base:
{kb if kb else "(empty - no relevant entry found)"}"""
    return call([
        {"role": "system", "content": system},
        {"role": "user", "content": message},
    ])

def step4_handoff_summary(message):
    prompt = f"""以下是一条需要人工处理的外语客户消息。请用中文输出结构化摘要，格式：
【语言】【问题类型】【客户诉求】【情绪等级 1-5】【建议处理动作】
注意：若客户提及 chargeback/拒付、法律行动或监管投诉，须在【建议处理动作】中标注"高优先级"并说明商业风险。
客户消息：{message}"""
    return call([{"role": "user", "content": prompt}], 300)

ESCALATE_TOPICS = {"complaint", "legal"}

def handle(message):
    print(f"\n{'='*60}\n[客户询盘] {message}\n")
    meta = step1_classify(message)
    print(f"[意图识别] {meta}")
    if meta.get("escalate") or meta.get("topic") in ESCALATE_TOPICS:
        print("[!] 触发转人工规则")
        print(f"[给人工客服的中文摘要]\n{step4_handoff_summary(message)}")
        return
    retrieved = step2_retrieve(message, meta.get("topic", "other"))
    print(f"[命中知识库条目] {[x['id'] for x in retrieved]}")
    print(f"[自动回复 {meta.get('language')}]\n{step3_answer(message, meta.get('language', 'en'), retrieved)}")

tests = [
    "Bonjour, combien de temps prend la livraison vers la France ?",
    "Wie kann ich meine Bestellung zurückgeben?",
    "This is unacceptable!! Third time my parcel is lost. I want to speak to a manager or I'll dispute the charge with my bank.",
    "Do you ship to Japan?"
]
for t in tests:
    handle(t)

"""## 幻觉测试（知识库锚定验证）

测试用例："Do you ship to Japan?"——知识库仅列出配送国家清单，未提及日本。
结果： 模型基于知识库正确回答"不配送日本"，未编造物流承诺。"仅基于知识库回答、不得虚构政策"的 prompt 约束在此用例上有效。

## 本 Demo 的边界（生产化差距）
本项目为验证多语言直接生成策略可行性的 MVP，非生产系统。生产化需补足：
embedding 向量检索（当前为 LLM 直选，知识库扩容后不可行）、多轮会话管理、订单/工单系统集成、自动化评测集与质检指标。

完整方案文档（含架构、ROI 测算、实施路线图）：[此处放 PDF/GitHub 链接]
"""